language: "es"

pipeline:
- name: "WhitespaceTokenizer"
- name: "RegexFeaturizer"
- name: "LanguageModelFeaturizer"
  model_name: "bert"
  model_weights: "dccuchile/bert-base-spanish-wwm-cased"
- name: "DIETClassifier"
  epochs: 150
  constrain_similarities: true
- name: "RegexEntityExtractor"
- name: "EntitySynonymMapper"
- name: "FallbackClassifier"
  threshold: 0.4
  ambiguity_threshold: 0.2
assistant_id: 20251023-202944-soft-hypothesis
policies:
- name: "RulePolicy"
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_gemini_fallback"
- name: "MemoizationPolicy"
  max_history: 5
- name: "TEDPolicy"
  max_history: 5
  epochs: 100
